// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:d1a65055-96ee-4cdb-bf21-2121fd96673e',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'pfp-hosting-mobilehub-502769725',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1eg12o4u5gzoy.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f021431df4bd43659d993057b0e088b4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '5784809e-ba43-45b1-a300-e8874f03fc74',
    'aws_project_name': 'PFP',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'pfp-mobilehub-502769725',
}

export default awsmobile;
